export const loginCredentils = {
  foo: {
    password: 'bar',
  },
}

export const limit = {
  large: 15,
  small: 10,
}

export const contacts = [
  { id: 0, name: 'FirstName0 LastName0', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 1, name: 'FirstName1 LastName1', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 2, name: 'FirstName2 LastName2', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 3, name: 'FirstName3 LastName3', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 4, name: 'FirstName4 LastName4', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 5, name: 'FirstName5 LastName5', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 6, name: 'FirstName6 LastName6', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 7, name: 'FirstName7 LastName7', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 8, name: 'FirstName8 LastName8', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 9, name: 'FirstName9 LastName9', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 10, name: 'FirstName10 LastName10', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 11, name: 'FirstName11 LastName11', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 12, name: 'FirstName12 LastName12', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 13, name: 'FirstName13 LastName13', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 14, name: 'FirstName14 LastName14', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 15, name: 'FirstName15 LastName15', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 16, name: 'FirstName16 LastName16', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 17, name: 'FirstName17 LastName17', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 18, name: 'FirstName18 LastName18', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 19, name: 'FirstName19 LastName19', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 20, name: 'FirstName20 LastName20', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 21, name: 'FirstName21 LastName21', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 22, name: 'FirstName22 LastName22', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 23, name: 'FirstName23 LastName23', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 24, name: 'FirstName24 LastName24', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 25, name: 'FirstName25 LastName25', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 26, name: 'FirstName26 LastName26', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 27, name: 'FirstName27 LastName27', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 28, name: 'FirstName28 LastName28', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 29, name: 'FirstName29 LastName29', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 30, name: 'FirstName30 LastName30', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 31, name: 'FirstName31 LastName31', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 32, name: 'FirstName32 LastName32', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 33, name: 'FirstName33 LastName33', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 34, name: 'FirstName34 LastName34', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 35, name: 'FirstName35 LastName35', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 36, name: 'FirstName36 LastName36', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 37, name: 'FirstName37 LastName37', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 38, name: 'FirstName38 LastName38', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 39, name: 'FirstName39 LastName39', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 40, name: 'FirstName40 LastName40', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 41, name: 'FirstName41 LastName41', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 42, name: 'FirstName42 LastName42', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 43, name: 'FirstName43 LastName43', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 44, name: 'FirstName44 LastName44', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 45, name: 'FirstName45 LastName45', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 46, name: 'FirstName46 LastName46', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 47, name: 'FirstName47 LastName47', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 48, name: 'FirstName48 LastName48', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 49, name: 'FirstName49 LastName49', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 50, name: 'FirstName50 LastName50', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 51, name: 'FirstName51 LastName51', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 52, name: 'FirstName52 LastName52', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 53, name: 'FirstName53 LastName53', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 54, name: 'FirstName54 LastName54', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 55, name: 'FirstName55 LastName55', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 56, name: 'FirstName56 LastName56', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 57, name: 'FirstName57 LastName57', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 58, name: 'FirstName58 LastName58', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 59, name: 'FirstName59 LastName59', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 60, name: 'FirstName60 LastName60', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 61, name: 'FirstName61 LastName61', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 62, name: 'FirstName62 LastName62', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 63, name: 'FirstName63 LastName63', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 64, name: 'FirstName64 LastName64', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 65, name: 'FirstName65 LastName65', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 66, name: 'FirstName66 LastName66', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 67, name: 'FirstName67 LastName67', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 68, name: 'FirstName68 LastName68', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' },
  { id: 69, name: 'FirstName69 LastName69', image: 'http://getdrawings.com/free-icon/contact-icon-images-63.png' } ]
